### ISSUE TITLE
Security Warning on Subscribe button

### ISSUE THREAD

**Issue by Ethan-Arrowood** [hackwitus/hackwit.us#45]
<img width="1148" alt="Screen Shot 2019-05-01 at 3 25 08 PM" src="https://user-images.githubusercontent.com/16144158/57037545-71c77e80-6c25-11e9-88c2-85479e2c28d6.png">

Whats up with this warning after clicking the subscribe button? Seems like an issue with `http` and `https`. Maybe it has something to do with the mailchimp button. If y'all can't figure it out let me know and I can jump in to try and remedy.

**Comment by Ethan-Arrowood** [comment]
Also I'm using FireFox

**Comment by corbinhak** [comment]
Fixed it!
